version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
      #    volumes:
      #- './services/users:/usr/src/app'
    #ports:
      #- 5001:5000
    expose:
      - '5000'   # why expose 5000 need a single quote here ?
    environment:
      # - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      #- APP_SETTINGS=project.config.DevelopmentConfig  # new
      - APP_SETTINGS=project.config.ProductionConfig  # new
      #- DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev  # new
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod  # new
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test  # new
    depends_on:  # new
      - users-db

  users-db:  # new
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    #ports:
      #- 5435:5432 
      # Postgres will be available on port 5435 on the host machine and 
      # on port 5432 for services running in other container
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users   # so boot sequence is user-db, users and then nginx
      - client

  client:
      container_name: client
      build:
        context: ./services/client
        dockerfile: Dockerfile-prod
        args:
          - NODE_ENV=production
          - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      ports:
        - '3007:80'
      depends_on:
        - users
