# base image
FROM python:3.7.2-alpine

# new
# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# new
# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh


# add app
COPY . /usr/src/app

# run server
# old command.
#CMD python manage.py run -h 0.0.0.0

# new
# run server - it will check if Postgres DB is up and then bring up local python app process
CMD ["/usr/src/app/entrypoint.sh"]
